version: "3.7"

services:
    bitzipbot:
        container_name: breezerbot
        hostname: breezerbot
        image: massmux/breezerbot
        restart: on-failure
        build:
                context: .
                dockerfile: Dockerfile
        volumes:
          #- ${PWD}/bot:/opt/breezerbot
                - ${PWD}/workdir:/opt/breezerbot/workdir
                - ${PWD}/qrdir:/opt/breezerbot/qrdir
                - ${PWD}/settings.ini:/opt/breezerbot/settings.ini
        working_dir: /opt/breezerbot
        entrypoint: /opt/breezerbot/entrypoint.sh
        environment:
                - TZ=Europe/Rome
        links:
                - redisdb


    redisdb:
        container_name: breezerbot-redisdb
        hostname: redisdb
        command: redis-server /usr/local/etc/redis/redis.conf
        restart: on-failure
        image: redis:5.0.12
        volumes:
                - ${PWD}/redisdata:/data
                - ${PWD}/redisconf:/usr/local/etc/redis


